// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/batteries/v1/sonnen/sonnen.proto

package sonnen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SonnenBatteriesService_GetSonnenStatus_FullMethodName   = "/batteries.v1.sonnen.SonnenBatteriesService/GetSonnenStatus"
	SonnenBatteriesService_GetLatestData_FullMethodName     = "/batteries.v1.sonnen.SonnenBatteriesService/GetLatestData"
	SonnenBatteriesService_GetPowerMeterData_FullMethodName = "/batteries.v1.sonnen.SonnenBatteriesService/GetPowerMeterData"
	SonnenBatteriesService_GetEnergyData_FullMethodName     = "/batteries.v1.sonnen.SonnenBatteriesService/GetEnergyData"
	SonnenBatteriesService_ChargeSonnen_FullMethodName      = "/batteries.v1.sonnen.SonnenBatteriesService/ChargeSonnen"
	SonnenBatteriesService_DischargeSonnen_FullMethodName   = "/batteries.v1.sonnen.SonnenBatteriesService/DischargeSonnen"
)

// SonnenBatteriesServiceClient is the client API for SonnenBatteriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SonnenBatteriesServiceClient interface {
	GetSonnenStatus(ctx context.Context, in *GetSonnenStatusRequest, opts ...grpc.CallOption) (*GetSonnenStatusResponse, error)
	GetLatestData(ctx context.Context, in *GetLatestDataRequest, opts ...grpc.CallOption) (*GetLatestDataResponse, error)
	GetPowerMeterData(ctx context.Context, in *GetPowerMeterDataRequest, opts ...grpc.CallOption) (*GetPowerMeterDataResponse, error)
	GetEnergyData(ctx context.Context, in *GetEnergyDataRequest, opts ...grpc.CallOption) (*GetEnergyDataResponse, error)
	ChargeSonnen(ctx context.Context, in *ChargeSonnenRequest, opts ...grpc.CallOption) (*ChargeSonnenResponse, error)
	DischargeSonnen(ctx context.Context, in *DischargeSonnenRequest, opts ...grpc.CallOption) (*DischargeSonnenResponse, error)
}

type sonnenBatteriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSonnenBatteriesServiceClient(cc grpc.ClientConnInterface) SonnenBatteriesServiceClient {
	return &sonnenBatteriesServiceClient{cc}
}

func (c *sonnenBatteriesServiceClient) GetSonnenStatus(ctx context.Context, in *GetSonnenStatusRequest, opts ...grpc.CallOption) (*GetSonnenStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSonnenStatusResponse)
	err := c.cc.Invoke(ctx, SonnenBatteriesService_GetSonnenStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonnenBatteriesServiceClient) GetLatestData(ctx context.Context, in *GetLatestDataRequest, opts ...grpc.CallOption) (*GetLatestDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestDataResponse)
	err := c.cc.Invoke(ctx, SonnenBatteriesService_GetLatestData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonnenBatteriesServiceClient) GetPowerMeterData(ctx context.Context, in *GetPowerMeterDataRequest, opts ...grpc.CallOption) (*GetPowerMeterDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPowerMeterDataResponse)
	err := c.cc.Invoke(ctx, SonnenBatteriesService_GetPowerMeterData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonnenBatteriesServiceClient) GetEnergyData(ctx context.Context, in *GetEnergyDataRequest, opts ...grpc.CallOption) (*GetEnergyDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnergyDataResponse)
	err := c.cc.Invoke(ctx, SonnenBatteriesService_GetEnergyData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonnenBatteriesServiceClient) ChargeSonnen(ctx context.Context, in *ChargeSonnenRequest, opts ...grpc.CallOption) (*ChargeSonnenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChargeSonnenResponse)
	err := c.cc.Invoke(ctx, SonnenBatteriesService_ChargeSonnen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonnenBatteriesServiceClient) DischargeSonnen(ctx context.Context, in *DischargeSonnenRequest, opts ...grpc.CallOption) (*DischargeSonnenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DischargeSonnenResponse)
	err := c.cc.Invoke(ctx, SonnenBatteriesService_DischargeSonnen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SonnenBatteriesServiceServer is the server API for SonnenBatteriesService service.
// All implementations must embed UnimplementedSonnenBatteriesServiceServer
// for forward compatibility.
type SonnenBatteriesServiceServer interface {
	GetSonnenStatus(context.Context, *GetSonnenStatusRequest) (*GetSonnenStatusResponse, error)
	GetLatestData(context.Context, *GetLatestDataRequest) (*GetLatestDataResponse, error)
	GetPowerMeterData(context.Context, *GetPowerMeterDataRequest) (*GetPowerMeterDataResponse, error)
	GetEnergyData(context.Context, *GetEnergyDataRequest) (*GetEnergyDataResponse, error)
	ChargeSonnen(context.Context, *ChargeSonnenRequest) (*ChargeSonnenResponse, error)
	DischargeSonnen(context.Context, *DischargeSonnenRequest) (*DischargeSonnenResponse, error)
	mustEmbedUnimplementedSonnenBatteriesServiceServer()
}

// UnimplementedSonnenBatteriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSonnenBatteriesServiceServer struct{}

func (UnimplementedSonnenBatteriesServiceServer) GetSonnenStatus(context.Context, *GetSonnenStatusRequest) (*GetSonnenStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSonnenStatus not implemented")
}
func (UnimplementedSonnenBatteriesServiceServer) GetLatestData(context.Context, *GetLatestDataRequest) (*GetLatestDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestData not implemented")
}
func (UnimplementedSonnenBatteriesServiceServer) GetPowerMeterData(context.Context, *GetPowerMeterDataRequest) (*GetPowerMeterDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPowerMeterData not implemented")
}
func (UnimplementedSonnenBatteriesServiceServer) GetEnergyData(context.Context, *GetEnergyDataRequest) (*GetEnergyDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnergyData not implemented")
}
func (UnimplementedSonnenBatteriesServiceServer) ChargeSonnen(context.Context, *ChargeSonnenRequest) (*ChargeSonnenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChargeSonnen not implemented")
}
func (UnimplementedSonnenBatteriesServiceServer) DischargeSonnen(context.Context, *DischargeSonnenRequest) (*DischargeSonnenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DischargeSonnen not implemented")
}
func (UnimplementedSonnenBatteriesServiceServer) mustEmbedUnimplementedSonnenBatteriesServiceServer() {
}
func (UnimplementedSonnenBatteriesServiceServer) testEmbeddedByValue() {}

// UnsafeSonnenBatteriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SonnenBatteriesServiceServer will
// result in compilation errors.
type UnsafeSonnenBatteriesServiceServer interface {
	mustEmbedUnimplementedSonnenBatteriesServiceServer()
}

func RegisterSonnenBatteriesServiceServer(s grpc.ServiceRegistrar, srv SonnenBatteriesServiceServer) {
	// If the following call pancis, it indicates UnimplementedSonnenBatteriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SonnenBatteriesService_ServiceDesc, srv)
}

func _SonnenBatteriesService_GetSonnenStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSonnenStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonnenBatteriesServiceServer).GetSonnenStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonnenBatteriesService_GetSonnenStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonnenBatteriesServiceServer).GetSonnenStatus(ctx, req.(*GetSonnenStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonnenBatteriesService_GetLatestData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonnenBatteriesServiceServer).GetLatestData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonnenBatteriesService_GetLatestData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonnenBatteriesServiceServer).GetLatestData(ctx, req.(*GetLatestDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonnenBatteriesService_GetPowerMeterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPowerMeterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonnenBatteriesServiceServer).GetPowerMeterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonnenBatteriesService_GetPowerMeterData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonnenBatteriesServiceServer).GetPowerMeterData(ctx, req.(*GetPowerMeterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonnenBatteriesService_GetEnergyData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnergyDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonnenBatteriesServiceServer).GetEnergyData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonnenBatteriesService_GetEnergyData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonnenBatteriesServiceServer).GetEnergyData(ctx, req.(*GetEnergyDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonnenBatteriesService_ChargeSonnen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeSonnenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonnenBatteriesServiceServer).ChargeSonnen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonnenBatteriesService_ChargeSonnen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonnenBatteriesServiceServer).ChargeSonnen(ctx, req.(*ChargeSonnenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonnenBatteriesService_DischargeSonnen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DischargeSonnenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonnenBatteriesServiceServer).DischargeSonnen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonnenBatteriesService_DischargeSonnen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonnenBatteriesServiceServer).DischargeSonnen(ctx, req.(*DischargeSonnenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SonnenBatteriesService_ServiceDesc is the grpc.ServiceDesc for SonnenBatteriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SonnenBatteriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "batteries.v1.sonnen.SonnenBatteriesService",
	HandlerType: (*SonnenBatteriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSonnenStatus",
			Handler:    _SonnenBatteriesService_GetSonnenStatus_Handler,
		},
		{
			MethodName: "GetLatestData",
			Handler:    _SonnenBatteriesService_GetLatestData_Handler,
		},
		{
			MethodName: "GetPowerMeterData",
			Handler:    _SonnenBatteriesService_GetPowerMeterData_Handler,
		},
		{
			MethodName: "GetEnergyData",
			Handler:    _SonnenBatteriesService_GetEnergyData_Handler,
		},
		{
			MethodName: "ChargeSonnen",
			Handler:    _SonnenBatteriesService_ChargeSonnen_Handler,
		},
		{
			MethodName: "DischargeSonnen",
			Handler:    _SonnenBatteriesService_DischargeSonnen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/batteries/v1/sonnen/sonnen.proto",
}
