// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type FastPowerDatum struct {
	RequestedTime         time.Time
	ReceivedTime          time.Time
	WriteTime             sql.NullTime
	Timestamp             time.Time
	Manufacturer          string
	ManufacturerSerial    string
	GenerationActivePower sql.NullString
	GridActivePower       sql.NullString
	GridReactivePower     sql.NullString
	BatteryActivePower    sql.NullString
	BatteryApparentPower  sql.NullString
	Soc                   sql.NullString
}

type HalfHourlyEnergyDatum struct {
	ID                 int64
	RequestedTime      time.Time
	ReceivedTime       time.Time
	WriteTime          sql.NullTime
	Timestamp          time.Time
	Manufacturer       string
	ManufacturerSerial string
	PvToHome           sql.NullString
	PvToBattery        sql.NullString
	PvToGrid           sql.NullString
	GridToHome         sql.NullString
	GridToBattery      sql.NullString
	BatteryToHome      sql.NullString
	BatteryToGrid      sql.NullString
}
